/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import coordinators.TransactionsCoordinator;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author youmna
 */
public class HomePage extends javax.swing.JFrame {

    private TransactionsCoordinator tCoordinator = new TransactionsCoordinator();

    /**
     * Creates new form NewJFrame
     */
    public HomePage() {
        initComponents();
        
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "mainPanel");
        jLabel2.setText(tCoordinator.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        checkBalanceBtn = new javax.swing.JButton();
        withdrawPageBtn = new javax.swing.JButton();
        depositPageBtn = new javax.swing.JButton();
        TransHistoryPageBtn = new javax.swing.JButton();
        addBeneficiaryPageBtn = new javax.swing.JButton();
        myBeneficiariesBtn = new javax.swing.JButton();
        transferMoneyPageBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        withdrawPanel = new javax.swing.JPanel();
        withdrawField = new javax.swing.JTextField();
        withdrawAmountLabel = new javax.swing.JLabel();
        withdrawLabel = new javax.swing.JLabel();
        withdrawBtn = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        depositField = new javax.swing.JTextField();
        depositAmountLabel = new javax.swing.JLabel();
        depositLabel = new javax.swing.JLabel();
        depositBtn = new javax.swing.JButton();
        checkBalancePanel = new javax.swing.JPanel();
        checkBalanceLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceAmountLabel = new javax.swing.JLabel();
        checkTransactionsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTable = new javax.swing.JTable();
        addBeneficiaryPanel = new javax.swing.JPanel();
        addBeneficiaryLabel = new javax.swing.JLabel();
        beneficiaryAccountNumLabel = new javax.swing.JLabel();
        beneficiaryAccountNumField = new javax.swing.JTextField();
        beneficiaryNameLabel = new javax.swing.JLabel();
        beneficiaryNameField = new javax.swing.JTextField();
        addBeneficiaryBtn = new javax.swing.JButton();
        myBeneficiariesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        beneficiariesTable = new javax.swing.JTable();
        transferMoneyPanel = new javax.swing.JPanel();
        transferMoneyLabel = new javax.swing.JLabel();
        transferBeneficiaryAccountLabel = new javax.swing.JLabel();
        transferMoneyAmountLabel = new javax.swing.JLabel();
        transferBeneficiaryNumField = new javax.swing.JTextField();
        transferAmountField = new javax.swing.JTextField();
        transferBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");

        menuPanel.setBackground(new java.awt.Color(153, 153, 153));

        checkBalanceBtn.setText("Check Balance");
        checkBalanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceBtnActionPerformed(evt);
            }
        });

        withdrawPageBtn.setText("Withdraw");
        withdrawPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawPageBtnActionPerformed(evt);
            }
        });

        depositPageBtn.setText("Deposit");
        depositPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositPageBtnActionPerformed(evt);
            }
        });

        TransHistoryPageBtn.setText("Transactions History");
        TransHistoryPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransHistoryPageBtnActionPerformed(evt);
            }
        });

        addBeneficiaryPageBtn.setText("Add Beneficiary");
        addBeneficiaryPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBeneficiaryPageBtnActionPerformed(evt);
            }
        });

        myBeneficiariesBtn.setText("My Beneficiaries");
        myBeneficiariesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBeneficiariesBtnActionPerformed(evt);
            }
        });

        transferMoneyPageBtn.setText("Transfer Money");
        transferMoneyPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMoneyPageBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Log out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(withdrawPageBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBalanceBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransHistoryPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBeneficiaryPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myBeneficiariesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferMoneyPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(checkBalanceBtn)
                .addGap(18, 18, 18)
                .addComponent(withdrawPageBtn)
                .addGap(18, 18, 18)
                .addComponent(depositPageBtn)
                .addGap(18, 18, 18)
                .addComponent(TransHistoryPageBtn)
                .addGap(18, 18, 18)
                .addComponent(addBeneficiaryPageBtn)
                .addGap(18, 18, 18)
                .addComponent(myBeneficiariesBtn)
                .addGap(18, 18, 18)
                .addComponent(transferMoneyPageBtn)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, java.awt.BorderLayout.LINE_START);

        homePanel.setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        homePanel.add(mainPanel, "mainPanel");

        withdrawPanel.setBackground(new java.awt.Color(204, 204, 204));

        withdrawAmountLabel.setText("Amount of Money");

        withdrawLabel.setText("Withdraw Money");

        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawPanelLayout = new javax.swing.GroupLayout(withdrawPanel);
        withdrawPanel.setLayout(withdrawPanelLayout);
        withdrawPanelLayout.setHorizontalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(withdrawAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(withdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withdrawBtn)
                    .addComponent(withdrawLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        withdrawPanelLayout.setVerticalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(withdrawLabel)
                .addGap(57, 57, 57)
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawAmountLabel)
                    .addComponent(withdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(withdrawBtn)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        homePanel.add(withdrawPanel, "withdrawPanel");

        depositPanel.setBackground(new java.awt.Color(204, 204, 204));

        depositAmountLabel.setText("Amount of Money");

        depositLabel.setText("Deposit Money");

        depositBtn.setText("Deposit");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositPanelLayout = new javax.swing.GroupLayout(depositPanel);
        depositPanel.setLayout(depositPanelLayout);
        depositPanelLayout.setHorizontalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(depositAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(depositBtn)
                    .addComponent(depositLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depositPanelLayout.setVerticalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(depositLabel)
                .addGap(56, 56, 56)
                .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(depositAmountLabel)
                    .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(depositBtn)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        homePanel.add(depositPanel, "depositPanel");

        checkBalancePanel.setBackground(new java.awt.Color(204, 204, 204));

        checkBalanceLabel.setText("Check Balance");

        balanceLabel.setText("You're Balance is:");

        javax.swing.GroupLayout checkBalancePanelLayout = new javax.swing.GroupLayout(checkBalancePanel);
        checkBalancePanel.setLayout(checkBalancePanelLayout);
        checkBalancePanelLayout.setHorizontalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGroup(checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkBalancePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(balanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balanceAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkBalancePanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(checkBalanceLabel)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        checkBalancePanelLayout.setVerticalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(checkBalanceLabel)
                .addGap(48, 48, 48)
                .addGroup(checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceLabel)
                    .addComponent(balanceAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        homePanel.add(checkBalancePanel, "checkBalancePanel");

        checkTransactionsPanel.setBackground(new java.awt.Color(204, 204, 204));

        transactionsTable.setBackground(new java.awt.Color(204, 204, 204));
        transactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Amount", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionsTable);

        javax.swing.GroupLayout checkTransactionsPanelLayout = new javax.swing.GroupLayout(checkTransactionsPanel);
        checkTransactionsPanel.setLayout(checkTransactionsPanelLayout);
        checkTransactionsPanelLayout.setHorizontalGroup(
            checkTransactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        checkTransactionsPanelLayout.setVerticalGroup(
            checkTransactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        homePanel.add(checkTransactionsPanel, "checkTransactionsPanel");

        addBeneficiaryPanel.setBackground(new java.awt.Color(204, 204, 204));

        addBeneficiaryLabel.setText("Add Beneficiary");

        beneficiaryAccountNumLabel.setText("Beneficiary Account No.");

        beneficiaryNameLabel.setText("Beneficiary Name");

        addBeneficiaryBtn.setText("Add");
        addBeneficiaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBeneficiaryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBeneficiaryPanelLayout = new javax.swing.GroupLayout(addBeneficiaryPanel);
        addBeneficiaryPanel.setLayout(addBeneficiaryPanelLayout);
        addBeneficiaryPanelLayout.setHorizontalGroup(
            addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBeneficiaryPanelLayout.createSequentialGroup()
                .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBeneficiaryPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beneficiaryAccountNumLabel)
                            .addComponent(beneficiaryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(beneficiaryAccountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beneficiaryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addBeneficiaryPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBeneficiaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBeneficiaryLabel))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        addBeneficiaryPanelLayout.setVerticalGroup(
            addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBeneficiaryPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(addBeneficiaryLabel)
                .addGap(33, 33, 33)
                .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beneficiaryAccountNumLabel)
                    .addComponent(beneficiaryAccountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addBeneficiaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beneficiaryNameLabel)
                    .addComponent(beneficiaryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(addBeneficiaryBtn)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        homePanel.add(addBeneficiaryPanel, "addBeneficiaryPanel");

        myBeneficiariesPanel.setBackground(new java.awt.Color(204, 204, 204));

        beneficiariesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Account Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(beneficiariesTable);

        javax.swing.GroupLayout myBeneficiariesPanelLayout = new javax.swing.GroupLayout(myBeneficiariesPanel);
        myBeneficiariesPanel.setLayout(myBeneficiariesPanelLayout);
        myBeneficiariesPanelLayout.setHorizontalGroup(
            myBeneficiariesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        myBeneficiariesPanelLayout.setVerticalGroup(
            myBeneficiariesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        homePanel.add(myBeneficiariesPanel, "myBeneficiariesPanel");

        transferMoneyPanel.setBackground(new java.awt.Color(204, 204, 204));

        transferMoneyLabel.setText("Transfer Money to Beneficiaries");

        transferBeneficiaryAccountLabel.setText("Beneficiary Account No.");

        transferMoneyAmountLabel.setText("Amount of Money");

        transferBtn.setText("Trasnfer");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferMoneyPanelLayout = new javax.swing.GroupLayout(transferMoneyPanel);
        transferMoneyPanel.setLayout(transferMoneyPanelLayout);
        transferMoneyPanelLayout.setHorizontalGroup(
            transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferMoneyPanelLayout.createSequentialGroup()
                .addGroup(transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transferMoneyPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferBeneficiaryAccountLabel)
                            .addComponent(transferMoneyAmountLabel))
                        .addGap(40, 40, 40)
                        .addGroup(transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferBeneficiaryNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transferMoneyPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(transferMoneyLabel))
                    .addGroup(transferMoneyPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(transferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        transferMoneyPanelLayout.setVerticalGroup(
            transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferMoneyPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(transferMoneyLabel)
                .addGap(37, 37, 37)
                .addGroup(transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferBeneficiaryAccountLabel)
                    .addComponent(transferBeneficiaryNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(transferMoneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferMoneyAmountLabel)
                    .addComponent(transferAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(transferBtn)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        homePanel.add(transferMoneyPanel, "transferMoneyPanel");

        getContentPane().add(homePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositPageBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "depositPanel");
    }//GEN-LAST:event_depositPageBtnActionPerformed

    private void checkBalanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "checkBalancePanel");
        balanceAmountLabel.setText(tCoordinator.getBalance() + " SR");
    }//GEN-LAST:event_checkBalanceBtnActionPerformed

    private void withdrawPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawPageBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "withdrawPanel");
    }//GEN-LAST:event_withdrawPageBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        if (!tCoordinator.isMoneyAmount(withdrawField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Amount of Money", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            double amount = Double.parseDouble(withdrawField.getText());
            if (tCoordinator.withdraw(amount)) {
                JOptionPane.showMessageDialog(this, amount + " SR Withdrawal has been done Successfully. Remaining: " + tCoordinator.getBalance() + " SR", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Denied Operation", "Denied", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        if (!tCoordinator.isMoneyAmount(depositField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Amount of Money", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            double amount = Double.parseDouble(depositField.getText());
            if (tCoordinator.deposit(amount)) {
                JOptionPane.showMessageDialog(this, amount + " SR Deposit has been done successfully. Balance: " + tCoordinator.getBalance() + " SR", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Denied Operation", "Denied", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_depositBtnActionPerformed

    private void TransHistoryPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransHistoryPageBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "checkTransactionsPanel");
        transactionsTable.setModel(tCoordinator.buildTransactionsTable());
        transactionsTable.setEnabled(false);
    }//GEN-LAST:event_TransHistoryPageBtnActionPerformed

    private void addBeneficiaryPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBeneficiaryPageBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "addBeneficiaryPanel");

    }//GEN-LAST:event_addBeneficiaryPageBtnActionPerformed

    private void addBeneficiaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBeneficiaryBtnActionPerformed
        if (!tCoordinator.isNumeric(beneficiaryAccountNumField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!tCoordinator.isRigestered(Integer.parseInt(beneficiaryAccountNumField.getText()))) {
            JOptionPane.showMessageDialog(this, "Account Number doesn't Exist", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!tCoordinator.isAlphabetic(beneficiaryNameField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Name", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int beneficiaryAccountNum = Integer.parseInt(beneficiaryAccountNumField.getText());
            String beneficiaryName = beneficiaryNameField.getText();
            tCoordinator.addBeneficiary(beneficiaryAccountNum, beneficiaryName);
            JOptionPane.showMessageDialog(this, beneficiaryName + " Has Been Added Successfully", "Succuss", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addBeneficiaryBtnActionPerformed

    private void myBeneficiariesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBeneficiariesBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "myBeneficiariesPanel");
        beneficiariesTable.setModel(tCoordinator.buildBeneficiariesTable());
        beneficiariesTable.setEnabled(false);
    }//GEN-LAST:event_myBeneficiariesBtnActionPerformed

    private void transferMoneyPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMoneyPageBtnActionPerformed
        CardLayout card = (CardLayout) homePanel.getLayout();
        card.show(homePanel, "transferMoneyPanel");
    }//GEN-LAST:event_transferMoneyPageBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        if (!tCoordinator.isNumeric(transferBeneficiaryNumField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Account Number", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!tCoordinator.isMoneyAmount(transferAmountField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Amount of Money", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!tCoordinator.isBeneficiary(Integer.parseInt(transferBeneficiaryNumField.getText()))) {
            JOptionPane.showMessageDialog(this, "Beneficary is not Registered as a Beneficary Account", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            double amount = Double.parseDouble(transferAmountField.getText());
            int beneficiaryNum = Integer.parseInt(transferBeneficiaryNumField.getText());
            if(tCoordinator.transferTo(amount, beneficiaryNum)){
                JOptionPane.showMessageDialog(this, amount + " SR Transferred has been done successfully. Balance: " + tCoordinator.getBalance() + " SR", "Success", JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(this, "Denied Operation", "Denied", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_transferBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
       tCoordinator.logOut();
       this.dispose();
       new SignInPage().setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransHistoryPageBtn;
    private javax.swing.JButton addBeneficiaryBtn;
    private javax.swing.JLabel addBeneficiaryLabel;
    private javax.swing.JButton addBeneficiaryPageBtn;
    private javax.swing.JPanel addBeneficiaryPanel;
    private javax.swing.JLabel balanceAmountLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTable beneficiariesTable;
    private javax.swing.JTextField beneficiaryAccountNumField;
    private javax.swing.JLabel beneficiaryAccountNumLabel;
    private javax.swing.JTextField beneficiaryNameField;
    private javax.swing.JLabel beneficiaryNameLabel;
    private javax.swing.JButton checkBalanceBtn;
    private javax.swing.JLabel checkBalanceLabel;
    private javax.swing.JPanel checkBalancePanel;
    private javax.swing.JPanel checkTransactionsPanel;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JButton depositBtn;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JButton depositPageBtn;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton myBeneficiariesBtn;
    private javax.swing.JPanel myBeneficiariesPanel;
    private javax.swing.JTable transactionsTable;
    private javax.swing.JTextField transferAmountField;
    private javax.swing.JLabel transferBeneficiaryAccountLabel;
    private javax.swing.JTextField transferBeneficiaryNumField;
    private javax.swing.JButton transferBtn;
    private javax.swing.JLabel transferMoneyAmountLabel;
    private javax.swing.JLabel transferMoneyLabel;
    private javax.swing.JButton transferMoneyPageBtn;
    private javax.swing.JPanel transferMoneyPanel;
    private javax.swing.JLabel withdrawAmountLabel;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JTextField withdrawField;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JButton withdrawPageBtn;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
